[package]
name = "m8b"
version = "0.3.2"
authors = ["Jeremiah Russell <jrussell@jerus.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
rand = "0.8.5"
