[package]
name = "m8b"
version = "0.1.1"
authors = ["Jeremiah Russell <jrussell@jerus.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"